# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: https://mohdasim.in
enforce_ssl: mohdasim.in
title: Mohd Asim Suhail | Mobile and Web Application developer. And more...
email: your-email@domain.com
description: An Experience of 2.5 years in structuring, developing and implementing interactive applications with all stages of the development cycle for dynamic Web and Mobile platform projects. Analytical, adaptive and technically proficient.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mohdasim.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AsimMnnit
github_username:  mohdasim

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
